language: php

sudo: false

git:
  depth: 2

cache:
  directories:
    - $HOME/.composer/cache

env:
  matrix:
    - PREFER_LOWEST=""
    - PREFER_LOWEST="--prefer-lowest"

php:
 - 7.4

install:
  - composer update --no-interaction --prefer-stable --prefer-dist --no-scripts --no-plugins $PREFER_LOWEST

script:
 - ./vendor/bin/phpunit --verbose
 - ./vendor/bin/psalm --show-info=true

matrix:
  fast_finish: true
