language: php

sudo: false

git:
  depth: 2

cache:
  directories:
    - $HOME/.composer/cache

env:
  matrix:
    - PREFER_LOWEST=""
    - PREFER_LOWEST="--prefer-lowest"

php:
 - 7.2
 - 7.3
 - 7.4

before_install:
 - composer install --dev --prefer-dist

script:
 - ./vendor/bin/phpunit --verbose
